### ISSUE TITLE
Mọi người có những vấn đề gì, những gì chưa làm thì viết ra đây. Sau đó chia task

### ISSUE THREAD

**Issue by hieuphamnhat** [quandapro/EducationQuality#1]

**Comment by hieudo-99** [comment]
- thêm, sửa tiêu chí của cơ sở giáo dục, chương trình đào tạo.
- tìm kiếm theo 1 tiêu chí nào đó.
- chức năng của admin: quản lý tài khoản.
- login/logout: chưa giữ được session khi login. Cụ thể, khi 1 user đã login, khi bấm vào các đường dẫn khác như trang chủ sẽ bị logout.
- vấn đề cần thảo luận: bảng đơn vị kiểm định liệu có thực sự cần thiết? Theo t thấy nên bỏ bảng đơn vị kiểm định để tránh phát sinh thêm các tính năng liên quan đến bảng này.

**Comment by hieudo-99** [comment]
về phần giao diện, t đã kêu duy làm các giao diện liên quan đến tiêu chí của cơ sở giáo dục và chương trình đào tạo. Nhạt thấy cần giao diện nào thì kêu luôn nhé.
