### ISSUE TITLE
Quản lý tiêu chí chương trình đào tạo

### ISSUE THREAD

**Issue by hieuphamnhat** [quandapro/EducationQuality#3]
Thêm, sửa, xem(Không làm xóa) các tiêu chí cho 1 chương trình đào tạo bất kỳ

**Comment by duynguyen9926** [comment]
T đã tạo giao diện xem tiêu chí cho cả ctđt và csgd, cả form để sửa điểm tiêu chí nhưng chưa có chức năng

**Comment by hieuphamnhat** [comment]
Deadline: 11:00pm (10/01/2021)

**Comment by duynguyen9926** [comment]
Xong chức năng sửa điểm tiêu chí cho cả ctđt và csgd

**Comment by hieuphamnhat** [comment]
Tối 8h30 demo nhé các bạn

**Comment by hieudo-99** [comment]
ok
